Vagrant.configure("2") do |config|

  
  vm_server_name = "aben-hamS"


  config.vm.box = "generic/alpine318"
  config.vm.synced_folder ".", "/vagrant", disabled: false

 
  config.vm.define vm_server_name do |server|

    server.vm.hostname = vm_server_name
    server.vm.network "private_network", ip: "192.168.56.110"

    
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", vm_server_name]
      vb.memory = "2048"
      vb.cpus = 1
    end
  
  end

  config.vm.provision "shell", path: "./setup.sh"


end
