Vagrant.configure("2") do |config|

  
  vm_server_name = "aben-hamS"


  config.vm.box = "generic/alpine318"
  config.vm.synced_folder ".", "/vagrant", disabled: false

 
  config.vm.define vm_server_name do |server|

    server.vm.hostname = vm_server_name
    server.vm.network "private_network", ip: "192.168.56.110"
    #config.vm.network "public_network", bridge: "wlp2s0"
    #server.vm.network "forwarded_port", guest: 8080, host: 8080
    #server.vm.network "forwarded_port", guest: 8081, host: 8081

    
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", vm_server_name]
      vb.memory = "2548"
      vb.cpus = 4
    end
  
  end

  #config.vm.provision "shell", path: "./setup.sh"


end
